GEA-13602: updates for AuthZ v1
pangeacyber/pangea-javascript pull request #1044
Opened 2024-04-30 18:11 UTC by kenany

Renamed "namespace" to "type" and changed endpoint paths to `/v1/`.

2024-04-30 19:06 UTC, pangea-andrest requested changes

2024-04-30 19:06 UTC, pangea-andrest commented on examples/authz/authz_cycle.mjs
> +            user: TYPE_FOLDER,
Same in `subject`?

2024-04-30 19:06 UTC, pangea-andrest commented on packages/pangea-node-sdk/tests/integration/authz.test.ts
> +      resource_namespace: TYPE_FOLDER,
Should update this filter?

2024-04-30 19:06 UTC, pangea-andrest commented on examples/authz/authz_cycle.mjs
> +        resource_user: TYPE_FOLDER,
```suggestion
        resource_type: TYPE_FOLDER,
```

2024-04-30 19:06 UTC, pangea-andrest commented on examples/authz/authz_cycle.mjs
> +        subject_user: TYPE_USER,
```suggestion
        subject_type: TYPE_USER,
```

2024-04-30 19:49 UTC, kenany commented on examples/authz/authz_cycle.mjs
> +            user: TYPE_FOLDER,
Oops. Need type-checking in the examples.

2024-04-30 19:49 UTC, kenany commented on packages/pangea-node-sdk/tests/integration/authz.test.ts
> +      resource_namespace: TYPE_FOLDER,
Updated.

2024-04-30 19:50 UTC, kenany commented on examples/authz/authz_cycle.mjs
> +        resource_user: TYPE_FOLDER,
Find-replace mistake. Fixed.

2024-04-30 19:50 UTC, kenany commented on examples/authz/authz_cycle.mjs
> +        subject_user: TYPE_USER,
Fixed.

2024-05-02 15:57 UTC, pangea-andrest approved these changes

2024-05-02 18:29 UTC, merged