Draft: GEA-14725: Add webcomponent wrappers
pangeacyber/pangea-javascript pull request #1143
Opened 2024-06-05 18:42 UTC by MichaelCombs28

2024-06-05 19:52 UTC, kenany requested changes

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/README.md
> +[![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://pangea.cloud/join-slack/)
Just drop the Slack badge.

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/README.md
> +              throw "only one component should be rendered";
I know it's just sample code but: throw errors, not strings.
```suggestion
              throw new Error("only one component should be rendered");
```

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/package.json
> +  "name": "pangea-webcomponents",
We'd probably do:
```suggestion
  "name": "@pangeacyber/webcomponents",
```

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/src/audit-log-viewer.tsx
> +console.log(window);
stray `console.log`

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/src/index.html
> +    <title>BetterTransfer</title>
copy-paste leftover?

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/README.md
> +You can install this by adding it to an `.html` file. You can copy paste the following in this directory and test using your browser:
Either in addition to this, or replacing this, we'll need instruction on how to use this _outside_ of this directory. i.e. actually installing the package via npm.

2024-06-05 19:52 UTC, kenany commented on packages/webcomponents/README.md
> +  <a href="https://pangea.cloud?utm_source=github&utm_medium=node-sdk" target="_blank" rel="noopener noreferrer">
```suggestion
  <a href="https://pangea.cloud?utm_source=github&utm_medium=webcomponents" target="_blank" rel="noopener noreferrer">
```

2024-06-05 19:53 UTC, kenany commented on packages/webcomponents/package-lock.json
_Personally_ I don't mind this, but note that the rest of the repo uses yarn (v1).

2024-06-05 20:42 UTC, MichaelCombs28 commented on packages/webcomponents/package-lock.json
I was using yarn v2, realized I was and switched to npm since we use `npm install` everywhere in the docs.

2024-06-06 17:02 UTC, cj-f commented
I believe you asked in slack how we want publishing to be handled, for our other react packages we have .gitlab-ci.yml files like ``` .react_mui_shared_base:
  image: node:20.12.2@sha256:3864be2201676a715cf240cfc17aec1d62459f92a7cbe7d32d1675e226e736c9
  before_script:
    - cd packages/react-mui-shared
    - yarn install --frozen-lockfile
    - apt-get -qq update
    - apt-get install -y jq
  cache:
    - key:
        files:
          - packages/react-mui-shared/yarn.lock
      paths:
        - packages/react-mui-shared/node_modules

publish_react_mui_shared:
  extends: .react_mui_shared_base
  stage: publish
  script:
    - cp ../../scripts/publish.sh .
    - echo "${NPMRC}" > .npmrc && ./publish.sh && rm .npmrc
    - rm publish.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - packages/react-mui-shared/**/*
      when: on_success
```

That basically deploys on main pipeline, if the version in package.json has been updated, I think could make sense to do similar here

2024-06-06 17:03 UTC, kenany submitted a review, later dismissed

2024-06-07 20:49 UTC, kenany approved these changes

2024-06-07 20:50 UTC, cj-f submitted a review, later dismissed

2024-06-07 21:44 UTC, cj-f approved these changes

2024-06-07 21:45 UTC, kenany submitted a review, later dismissed

2024-06-08 03:42 UTC, kenany approved these changes

2024-06-09 21:41 UTC, merged