PAN-15594: revision of typedoc
pangeacyber/pangea-javascript pull request #1262
Opened 2024-07-11 19:04 UTC by pangea-apoorva

2024-07-24 15:53 UTC, cj-f commented on packages/react-mui-audit-log-viewer/src/AuditLogViewer.tsx
> +  /** Trigger search on component mount. By default searchOnChange triggers a search, but if it is disabled then searchOnFilterChange can be enabled */
/** Flag to control if onSearch callback should be trigger on filter or sort changes. Default: true. Set to false if search should only be triggered when the Search button is clicked */

2024-07-24 15:53 UTC, cj-f commented on packages/react-mui-audit-log-viewer/src/AuditLogViewer.tsx
>    searchOnMount?: boolean;
/** Flag to control is onSearch callback should be trigger on component mount. Set to false to prevent search on component load. Defaults true. */

2024-07-24 15:56 UTC, cj-f commented on packages/react-mui-audit-log-viewer/src/AuditLogViewer.tsx
> +  /** Called when the user requests to download results  */
Should mention similar proxy line. It is repetitive but I think better to be explicit

2024-07-24 16:45 UTC, kenany requested changes

2024-07-24 16:45 UTC, kenany commented on packages/react-auth/package.json
> +    "build-docs": "yarn typedoc --plugin typedoc-plugin-rename-defaults",
Unnecessary `yarn` invocation.
```suggestion
    "build-docs": "typedoc --plugin typedoc-plugin-rename-defaults",
```

2024-07-24 16:45 UTC, kenany commented on packages/react-auth/package.json
> +    "build-docs": "yarn typedoc --plugin typedoc-plugin-rename-defaults",
Specifying the typedoc-plugin-rename-defaults plugin can be moved to `typedoc.json`.

2024-07-24 16:45 UTC, kenany commented on packages/react-auth/src/AuthNFlow/client.ts
> +   * @param {FlowStart} data The intial flow data to start with
```suggestion
   * @param {FlowStart} data The initial flow data to start with
```

2024-07-24 16:45 UTC, kenany commented on packages/react-auth/src/AuthNFlow/client.ts
> +   * @param {FlowStart} data The intial flow data to start with
```suggestion
   * @param {FlowStart} data The initial flow data to start with
```

2024-07-24 16:45 UTC, kenany commented on packages/react-auth/src/AuthProvider/index.tsx
> +/** const SESSION_DATA_KEY = "pangea-authn"; */
🤷‍♀️

2024-07-27 20:24 UTC, kenany approved these changes

2024-07-29 16:41 UTC, kenany commented on packages/react-auth/src/ComponentAuthProvider/index.tsx
> + * @returns React.Context<ComponentAuthContextType>
Uh, TS is telling me that it returns a `ComponentAuthContextType`, but okay.

2024-07-29 16:48 UTC, pangea-north commented on packages/react-auth/src/ComponentAuthProvider/index.tsx
> + * @returns React.Context<ComponentAuthContextType>
I think Glenn will need to weigh in on this one. I haven't actually used these libs before so there's a lot of unknowns to me

2024-07-29 16:56 UTC, kenany approved these changes

2024-07-29 17:00 UTC, kenany approved these changes

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/ComponentAuthProvider/index.tsx
> + * @returns React.Context<ComponentAuthContextType>
The component provider doesn't work any more, since it was built for the v1 APIs. We should probably call that out.

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    identity: string;
User ID of the token owner

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    type: string;
Type of token: `user` for active token, `session` for refresh token.

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    life: string;
Time in seconds until the token expires.

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    expire: string;
Token expiration timestamp in ISO 8601 format

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    scopes?: string[];
Should hide this for now, since there's no way to set scopes yet.

2024-07-29 17:14 UTC, ggallien13 commented on packages/react-auth/src/types.ts
>    scopes?: string[];
When the token was created, in ISO 8601 format.

2024-07-31 14:15 UTC, kenany approved these changes

2024-08-01 20:47 UTC, cj-f approved these changes

2024-08-02 20:33 UTC, merged